name: Deploy Nuxt 4 to S3

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Static Site
        run: npm run generate

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy lên dev khi push vào nhánh develop
      - name: Deploy to Staging S3
        if: github.ref == 'refs/heads/develop'
        run: |
          aws s3 sync .output/public s3://npc-corporate-dev --delete

      # Invalidate CloudFront Cache
      - name: CloudFront Invalidation
        if: success()
        run: |
          # Logic chọn ID Distribution dựa trên branch
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            DIST_ID=${{ secrets.CLOUDFRONT_DEV_ID }}
          else
            DIST_ID=${{ secrets.CLOUDFRONT_DEV_ID }}
          fi
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
